field: 5d0915dc-758f-4f02-a0e6-3505b199c8e4 # Content Builder
fieldLayouts:
  4a054d17-9b74-44ad-9b6b-d205a626bf9a:
    tabs:
      -
        elements:
          -
            fieldUid: 0a99b43e-940f-49e7-a5f6-664ce7b6a902 # Title Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1abb0346-010b-45fd-bec0-993a7d226299 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 429d11ce-b6df-4ca1-a53b-5c9b8f04cc8b # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e9620a13-02d3-40a2-857b-7ab26abaedfc # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 52ae72c6-26f5-4db1-832e-71dd2d2aa0f9 # Text Vertical Alignment
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 32dc6c82-9422-460d-8097-ec1db2e1f313 # Media
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e570d95a-0daf-43c4-93cd-19cf513a01bd # Media Position
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 8011ea88-1943-4a4c-ba26-1191373554b2 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  0a99b43e-940f-49e7-a5f6-664ce7b6a902: # Title Top
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitleTop
    instructions: ''
    name: 'Title Top'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  1abb0346-010b-45fd-bec0-993a7d226299: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '1'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  32dc6c82-9422-460d-8097-ec1db2e1f313: # Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemMedia
    instructions: ''
    name: Media
    searchable: false
    settings:
      contentTable: '{{%stc_2_itemmedia}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  52ae72c6-26f5-4db1-832e-71dd2d2aa0f9: # Text Vertical Alignment
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemTextVerticalAlignment
    instructions: ''
    name: 'Text Vertical Alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - top
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  429d11ce-b6df-4ca1-a53b-5c9b8f04cc8b: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Full.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  8011ea88-1943-4a4c-ba26-1191373554b2: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        4: entry
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: typedlinkfield\fields\LinkField
  e570d95a-0daf-43c4-93cd-19cf513a01bd: # Media Position
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemImagePosition
    instructions: ''
    name: 'Media Position'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e9620a13-02d3-40a2-857b-7ab26abaedfc: # Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemBackgroundColor
    instructions: ''
    name: 'Background Color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Light Blue'
            -
              - value
              - light
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: typeTextMedia
name: 'Text / Media'
sortOrder: 2
