field: e8ec13a1-85d1-4d6a-94e6-9c674b7a7693 # Content Builder
fieldLayouts:
  c8f9f70e-2591-4b13-9356-2417f1a7208f:
    tabs:
      -
        elements:
          -
            fieldUid: 6dc49670-1ea3-4405-a97a-3feb90e27b9d # Title Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 56094a03-f310-4658-b66a-3bfa633e2efb # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c089818a-1a2d-40e6-9b25-d203829b4f6d # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c69ce98a-2448-442f-8edd-f749c2ebdc7e # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: c3f168bf-7632-46e6-85e1-82c3f9c3476a # Text Vertical Alignment
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: cfbc3eea-5919-454a-89cd-d6b126eb23a8 # Media
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4431be45-e608-4eb5-bb30-defe9e525cf6 # Media Position
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: c3222bb0-c190-4d16-9d33-2b6e47525810 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  6dc49670-1ea3-4405-a97a-3feb90e27b9d: # Title Top
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitleTop
    instructions: ''
    name: 'Title Top'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4431be45-e608-4eb5-bb30-defe9e525cf6: # Media Position
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemImagePosition
    instructions: ''
    name: 'Media Position'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  56094a03-f310-4658-b66a-3bfa633e2efb: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '1'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c089818a-1a2d-40e6-9b25-d203829b4f6d: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Full.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c3f168bf-7632-46e6-85e1-82c3f9c3476a: # Text Vertical Alignment
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemTextVerticalAlignment
    instructions: ''
    name: 'Text Vertical Alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - top
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c69ce98a-2448-442f-8edd-f749c2ebdc7e: # Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemBackgroundColor
    instructions: ''
    name: 'Background Color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Light Blue'
            -
              - value
              - light
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c3222bb0-c190-4d16-9d33-2b6e47525810: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        4: entry
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  cfbc3eea-5919-454a-89cd-d6b126eb23a8: # Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemMedia
    instructions: ''
    name: Media
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 67339eb1-4f0f-467d-9605-027b6d1ea9bf # Media
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_itemmedia}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: typeTextMedia
name: 'Text / Media'
sortOrder: 2
