columnSuffix: lykoqskx
contentColumnType: text
fieldGroup: 56eaa975-ca03-4a1e-82b5-0a7b2321e6b0 # Company Info
handle: fieldAddressLine1
instructions: ''
name: 'Address Line 1'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
