columnSuffix: null
contentColumnType: text
fieldGroup: 9cb44f64-2eb1-4baa-b798-178dbca84cb7 # SEO
handle: fieldMetaDescription
instructions: 'The meta description is a snippet of up to about 155 characters – a tag in HTML – which summarizes a page’s content. Search engines show it in search results mostly when the searched-for phrase is within the description.'
name: 'Meta Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 155
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
