columnSuffix: null
contentColumnType: text
fieldGroup: 9cb44f64-2eb1-4baa-b798-178dbca84cb7 # SEO
handle: fieldMetaTitle
instructions: 'A title tag is an HTML element that specifies the title of a web page. Title tags are displayed on search engine results pages (SERPs) as the clickable headline for a given result, and are important for usability, SEO, and social sharing. The title tag of a web page is meant to be an accurate and concise description of a page''s content.'
name: 'Meta Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 60
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
