columnSuffix: null
contentColumnType: string(2048)
fieldGroup: 9cb44f64-2eb1-4baa-b798-178dbca84cb7 # SEO
handle: fieldOgDescription
instructions: ''
name: 'OG Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 512
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
