columnSuffix: null
contentColumnType: string
fieldGroup: 6bf679bc-2009-4681-a877-d3285c36f19b # Common
handle: fieldHomeBanner
instructions: ''
name: 'Home Banner'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 30f7dd35-ad08-4025-9d33-15561888bb91
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 40118880-62d4-4fbf-8042-a6ae185ec517
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_fieldhomebanner}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: 1
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
