columnSuffix: null
contentColumnType: string(128)
fieldGroup: 9cb44f64-2eb1-4baa-b798-178dbca84cb7 # SEO
handle: fieldOgAuthor
instructions: ''
name: 'OG author'
searchable: false
settings:
  byteLimit: null
  charLimit: 32
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
