columnSuffix: null
contentColumnType: string
fieldGroup: 56eaa975-ca03-4a1e-82b5-0a7b2321e6b0 # Company Info
handle: fieldFavicon
instructions: 'The favicon.ico for this website'
name: Favicon
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:746742b8-9eb5-47c0-b1c0-b49338783f9d' # images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: thumbs
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:746742b8-9eb5-47c0-b1c0-b49338783f9d' # images
  singleUploadLocationSubpath: logo
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
