columnSuffix: inyvviyx
contentColumnType: string(128)
fieldGroup: 7f31d1d3-eb01-43ca-95ad-3f97fd85cf53 # SEO
handle: fieldOgAuthor
instructions: ''
name: 'OG author'
searchable: false
settings:
  byteLimit: null
  charLimit: 32
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
