columnSuffix: tabbakai
contentColumnType: string
fieldGroup: 56eaa975-ca03-4a1e-82b5-0a7b2321e6b0 # Company Info
handle: fieldEmailAddress
instructions: ''
name: 'Email Address'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
