columnSuffix: quqbbqkc
contentColumnType: text
fieldGroup: 7f31d1d3-eb01-43ca-95ad-3f97fd85cf53 # SEO
handle: fieldMetaDescription
instructions: 'The meta description is a snippet of up to about 155 characters – a tag in HTML – which summarizes a page’s content. Search engines show it in search results mostly when the searched-for phrase is within the description.'
name: 'Meta Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 155
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
