columnSuffix: txhvxotz
contentColumnType: text
fieldGroup: 6bf679bc-2009-4681-a877-d3285c36f19b # Common
handle: fieldText
instructions: ''
name: Text
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: 1
  multiline: 1
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
