columnSuffix: null
contentColumnType: string
fieldGroup: 6bf679bc-2009-4681-a877-d3285c36f19b # Common
handle: fieldBannerImage
instructions: ''
name: 'Banner Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:39767a10-7f83-47f1-8e46-4191420cb937' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:39767a10-7f83-47f1-8e46-4191420cb937' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:39767a10-7f83-47f1-8e46-4191420cb937' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
