field: 906032d5-2d9a-45bf-a447-dd5bf81760ff # Legal Nav
fieldLayouts:
  81e94590-b26a-4d37-aa19-e702a13d6586:
    tabs:
      -
        elements:
          -
            fieldUid: 947d68af-bd21-4c25-9fc0-bea523350f96 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e5725bbe-8eaa-4f46-8796-b20a9321d227 # Privacy Policy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  947d68af-bd21-4c25-9fc0-bea523350f96: # Link
    columnSuffix: cbnreyef
    contentColumnType: text
    fieldGroup: null
    handle: itemLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      allowCustomText: 1
      allowTarget: ''
      allowedLinkNames:
        4: entry
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: typedlinkfield\fields\LinkField
  e5725bbe-8eaa-4f46-8796-b20a9321d227: # Privacy Policy
    columnSuffix: thrzgdhx
    contentColumnType: boolean
    fieldGroup: null
    handle: itemPrivacyPolicy
    instructions: ''
    name: 'Privacy Policy'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
