fieldLayouts:
  abc96498-1219-4da0-8984-411dcb610a01:
    tabs:
      -
        elements:
          -
            fieldUid: 04c8d40c-466c-43af-831f-633c3b8c16ee # Main Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 25640e0f-f12b-4b8b-811f-e910b9f6099c # Footer Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0bdaa3c3-c4f3-458c-9fdb-988f1e9ce6b3 # Footer Highlight Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Footer
        sortOrder: 2
      -
        elements:
          -
            fieldUid: b1798a9a-6b6a-4d28-ac64-fed948463639 # Legal Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Legal
        sortOrder: 3
handle: globalNavigation
name: Navigation
sortOrder: 3
