fieldLayouts:
  fe87d92e-2537-4786-b80b-2ad119b41922:
    tabs:
      -
        elements:
          -
            fieldUid: f2294c0a-c3b6-4abe-ad5b-29d196b3893b # Address Line 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b6e0ac43-9540-4a47-8081-000d36681d5e # Address Line 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 377455a0-174e-4a76-9e47-6dee2b92801a # Address Line 3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f99e99cc-dae2-473e-ba4c-e98eea5ef796 # Company Baseline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 1bc335c1-25cf-44c7-ada3-cd7fbd3caf10 # Company Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 10688c27-74dd-43fd-bbe7-eee36d6c5363 # Email Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 9337590f-ea60-4217-a860-a496cc7ca9b3 # Telephone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 9acb56d7-287a-4a76-8b96-47468891dc74 # Linked In
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Details
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 961a322a-8161-4e1c-9906-a5e7ce548f2f # Logo
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 52936b9e-6123-4fbb-8269-ea2ad87d7269 # Logo Footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 360e97ad-1eb8-4861-820c-acb1f4badc1d # Favicon
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f39b071e-b23f-4a0b-9733-e170e72926b9 # Touch Icon
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Logo
        sortOrder: 2
      -
        elements:
          -
            fieldUid: f9227f0d-095b-47fa-b364-b16da4d9c9f4 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7d1543a1-678b-476a-b690-891c72786822 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e3cd1c4b-6b46-4cf5-a5a7-5fd450558464 # OG Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b16f4ff-58a1-4816-8071-be914f6b1c87 # OG Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 244b20a6-6ded-48b8-99ee-da16dd37bf45 # OG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2827bb9b-5326-4bea-bf8b-29d20dbffa5c # OG Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: globalCompanyInfo
name: 'Company Info'
sortOrder: 2
