defaultPlacement: end
enableVersioning: true
handle: errorPages
name: 'Error Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - '{slug}'
      -
        - urlFormat
        - pages/_entry
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  20991694-db86-4d2a-b2a1-d6ac860928bc: # BOA EN
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: 6ce9062d-d9a9-472d-babe-6b4b73ea4859
type: structure
