defaultPlacement: end
enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - '{slug}'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e00c4aea-76af-41ef-9d65-b6e755f0b74b: # BOA Blueprint
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
