defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  20991694-db86-4d2a-b2a1-d6ac860928bc: # BOA EN
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
