defaultPlacement: end
enableVersioning: true
handle: legalPages
name: 'Legal Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - '{slug}'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e00c4aea-76af-41ef-9d65-b6e755f0b74b: # BOA Blueprint
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: 0bf9d20e-5003-4534-a0b7-177da75398a4
type: structure
