defaultPlacement: end
enableVersioning: true
handle: legalPages
name: 'Legal Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - '{slug}'
      -
        - urlFormat
        - pages/_entry
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  20991694-db86-4d2a-b2a1-d6ac860928bc: # BOA EN
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: e867b7d3-cb90-446b-a89e-4f08d8323935
type: structure
