defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  20991694-db86-4d2a-b2a1-d6ac860928bc: # BOA EN
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: fbaac2ab-dedc-4c82-aa8a-7652291e4fc9
type: structure
